#%RAML 1.0
title: Example API
version: v1
baseUri: https://domain.com

annotationTypes:
  annotationTest: nil
  deprecated: string
  clearanceLevel:
    properties:
      level:
        enum: [ low, medium, high ]
        required: true
      signature:
        pattern: "\\d{3}-\\w{12}"
        required: true
      id:
        type: integer
        description: Id of the supervisor
/test:
  get:
    headers:
      x-page:
        (deprecated): This header will be replaced with query parameter `page`
        description: Specify the page that you want to retrieve
        type:        integer
        required:    true
        example:     1
      x-per_page:
        (deprecated): |
          This header will be removed in future release of this API.
          Please, use `pageLimit` query parameter intead.

          **Note:** This header will be in use until Nov 2020 according to our
          deprecation policy.
        description: Specify the amount of items that will be retrieved per page
        type:        integer
        minimum:     10
        maximum:     200
        default:     30
        example:     50
        displayName: Per page
      x-type:
        (annotationTest):
        description: Specify the amount of items that will be retrieved per page
        type:        string
        enum:       [type 1, type 2, type 3]
        required: false
        pattern: type\s\d
        minLength: 5
        maxLength: 6
        default:     type 1
        example:     type 2
        displayName: Per page
      x-other:
        type: boolean
        default: true
        example: false
        description: Either `true` or `fals`. You choose.
      x-a-date:
        displayName: A date
        type: date-only
        example: 2017-06-27
        (clearanceLevel):
          level: high
          signature: 230-ghtwvfrs1itr
          id: 123
      x-empty-default:
        type: string
        default: ""
      x-zero-number:
        type: number
        default: 0
