#%RAML 0.8
title: My 0.8 RAML API
baseUri: http://domain.mulesoft.com/mocks/
version: api-console
traits:
    -
        secured:
            displayName: secured
    -
        common_errors:
            displayName: common_errors
/quote/time:
    description: Get an arrival time quote
    is: [secured, common_errors]
    post:
        description: All requests that require api key
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                      "start_address" : "35-37 William Road, London, NW1 3ER",
                      "services" : [
                          {
                            "code" : "OneFourPassengers"
                          },
                          {
                           "code" : "FiveSixPassengers"
                          }
                      ],
                      "locations" : [
                          {
                             "long" : -0.139435,
                             "lat"  : 51.526972
                          }
                        ]
                      }
            application/xml:
              example: |
                <?xml version='1.0' encoding='UTF-8'?>
                <data>
                  <start-address><![CDATA[35-37 William Road, London, NW1 3ER]]></start-address>
                  <services>
                    <service>
                      <code>OneFourPassengers</code>
                    </service>
                    <service>
                      <code>FiveSixPassengers</code>
                    </service>
                  </services>
                  <locations>
                    <location>
                      <lat>-0.139435</lat>
                      <lon>51.526972</lon>
                    </location>
                  </locations>
                </data>
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                              "location" : "35-37 William Road , London , NW1 3ER",
                              "lat" : 51.52199935913086,
                              "long" : -0.14198000729084015,
                              "times" : [
                                {
                                  "service": "OneFourPassengers",
                                  "eta": 5
                                },{
                                  "service": "FiveSixPassengers",
                                  "eta": 10
                                }
                              ],
                              "session": "abc123def123"
                            }
                    application/xml:
                      example: |
                        <?xml version='1.0' encoding='UTF-8'?>
                        <data>
                          <location><![CDATA[35-37 William Road, London, NW1 3ER]]></location>
                          <lat>51.52199935913086</lat>
                          <lon>-0.14198000729084015</lon>
                          <times>
                            <time>
                              <service>OneFourPassengers</service>
                              <eta>5</eta>
                            </time>
                          </times>
                        </data>
                      schema: |
                        <xs:schema attributeFormDefault="unqualified"
                                   elementFormDefault="qualified"
                                   xmlns:xs="http://www.w3.org/2001/XMLSchema">
                          <xs:element name="data">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="location"/>
                                <xs:element type="xs:double" name="lat"/>
                                <xs:element type="xs:double" name="lon"/>
                                <xs:element name="times">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="time">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element type="xs:string" name="service"/>
                                            <xs:element type="xs:integer" name="eta"/>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:schema>
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid email address",
                              "transaction_id": "ABC123"
                            }
                    application/xml:
                      schema: |
                        <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
                          <xs:element name="data">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:short" name="status"/>
                                <xs:element type="xs:string" name="code"/>
                                <xs:element type="xs:string" name="message"/>
                                <xs:element type="xs:string" name="transaction-id"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:schema>
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout",
                              "transaction_id": "ABC123"
                            }
    /{serviceCode}:
      description: Get an arrival time quote for an unique service code.
      uriParameters:
        serviceCode:
          description: An unique service code pre-defined in Acme LTD.
          example: "OneFourPassengers"
      post:
        description: An unique service code in the URI.
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                      "start_address": "35-37 William Road, London, NW1 3ER",
                      "locations": [
                        {
                          "long": -0.139435,
                          "lat": 51.526972
                        }
                      ]
                    }
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                              "location" : "35-37 William Road , London , NW1 3ER",
                              "lat" : 51.526972,
                              "long" : -0.139435,
                              "times" : {
                                "service": "OneFourPassengers",
                                "eta": 5
                              },
                              "session": "abc123def123"
                            }
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid service code",
                              "transaction_id": "ABC123"
                            }
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload. This endpoint doesn't accept 'services'. Remove the services array.",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout.",
                              "transaction_id": "ABC123"
                            }
/quote/nearby:
    description: Get an array of neaby Drivers
    is: [secured, common_errors]
    post:
        description: All requests that require api key
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                      "locations" : [
                          {
                             "long" : -0.139435,
                             "lat"  : 51.526972
                          }
                        ],
                      "radius" : 100
                      }
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                              "drivers" : [
                                {
                                  "name" : "MOVSESYAN, RUBEN",
                                  "id" : 175000000000086347,
                                  "latitude" : 51.52199935913086,
                                  "longitude" : -0.14198000729084015,
                                  "telephone" : "07445448483",
                                  "vehicleModel" : "FORD GALAXY",
                                  "vehicleRegNo" : "LT62FNO"
                                }, {
                                  "name" : "OLANIYI, MICHAEL",
                                  "id" : 175000000000086473,
                                  "latitude" : 51.5224494934082,
                                  "longitude" : -0.14305999875068665,
                                  "telephone" : "07852127257",
                                  "vehicleModel" : "FORD GALAXY",
                                  "vehicleRegNo" : "LS11LPN"
                                }
                              ]
                            }
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid email address",
                              "transaction_id": "ABC123"
                            }
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout",
                              "transaction_id": "ABC123"
                            }
/quote/price:
    description: Get a price and arrival time quote
    is: [secured, common_errors]
    post:
        description: All requests that require api key
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                     "pickup_dt" : "2016-03-01T09:00:00+01:00",
                     "promo_code": "DISCOUNT10",
                     "payment_method" : "Cash",
                     "start_address" : "35-37 William Road, London, NW1 3ER",
                     "services" : [
                         {
                           "code" : "OneFourPassengers"
                         },
                         {
                          "code" : "FiveSixPassengers"
                         }
                     ],
                     "locations" : [
                         {
                            "long" : -0.139435,
                            "lat"  : 51.526972
                         },
                         {
                            "long" : -0.239435,
                            "lat"  : 51.326972
                         },
                         {
                            "long" : -0.339435,
                            "lat"  : 51.526972
                         }
                       ]
                     }
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                            "request_id": "123abc123def",
                            "locations" : [
                                 {
                                   "address": "35-37 William Road , London , NW1 3ER",
                                   "lat": 51.521999,
                                   "long": -0.141980
                                  },
                                  {
                                    "address": "Euston Railway Station, London, NW1 2DU",
                                    "lat": 51.528848,
                                    "long": -0.132828
                                  }
                             ],
                             "quotes" : [
                              {
                                "service": "OneFourPassengers",
                                "quote_id": "12345",
                                "total_price": 45.23,
                                "price": 45.23,
                                "discount": 0.00,
                                "vat": 0.00,
                                "currency": "GBP",
                                "eta": 5,
                                "payment_token": "abc123def456",
                                "payment_url": "http://payments.acme.ltd/payments/id=12345&token=abc123def456"
                              },
                              {
                                "service": "FiveSixPassengers",
                                "quote_id": "67890",
                                "total_price": 52.23,
                                "price": 52.23,
                                "discount": 0.00,
                                "vat": 0.00,
                                "currency": "GBP",
                                "eta": 15,
                                "payment_token": "abc123def456",
                                "payment_url": "http://payments.acme.ltd/payments/id=67890&token=abc123def456"
                              }
                              ]
                            }
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid email address",
                              "transaction_id": "ABC123"
                            }
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout",
                              "transaction_id": "ABC123"
                            }
    /{serviceCode}:
      uriParameters:
        serviceCode:
          description: This is a pre-defined service code in Acme LTD.
          example: "OneFourPassengers"
      description: Get the quote price for an unique service code.
      post:
        description: An unique and valid service code in the URI.
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                      "pickup_dt" : "2016-08-01T09:00:00+01:00",
                      "promo_code" : "DISCOUNT10",
                      "payment_method" : "Account",
                      "start_address" : "35-37 William Road, London, NW1 3ER",
                      "locations" : [
                        {
                              "address" : "Heathrow, Term 1 (domestic)",
                              "name" : "Heathrow, Term 1 (domestic)",
                              "source" : "Airport",
                              "town" : "London",
                              "postcode" : "TW6 1AP",
                              "id" : 62,
                              "lat" : 51.471959,
                              "long" : -0.452201
                          }, {
                              "long" : -0.239435,
                              "lat" : 51.326972
                          }, {
                              "long" : -0.339435,
                              "lat" : 51.526972
                        }
                        ]
                    }
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                              "request_id": "2c31a508-f974-4b4e-8403-c6dea5ef37a1",
                              "locations": [
                                {
                                  "address": "Heathrow, Term 1 (domestic)",
                                  "lat": 51.471959,
                                  "long": -0.452201,
                                  "source": "Airport"
                                },
                                {
                                  "address": "107 COLLEGE RD, EPSOM KT17 4JA, UK",
                                  "lat": 51.3264481,
                                  "long": -0.2406635,
                                  "source": "GOOGLE"
                                },
                                {
                                  "address": "25 RIVERSIDE CL, LONDON W7 1BY, UK",
                                  "lat": 51.5271513,
                                  "long": -0.3388765,
                                  "source": "GOOGLE"
                                }
                              ],
                              "quotes":
                                {
                                  "service": "OneFourPassengers",
                                  "quote_id": "cad60a10-0469-4443-bb74-10726e9553d9",
                                  "total_price": 76.3,
                                  "price": 86.3,
                                  "discount": 10,
                                  "vat": 0,
                                  "currency": "GBP",
                                  "eta": 21,
                                  "payment_token": "N/A",
                                  "payment_url": "N/A"
                                }
                            }
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid service code",
                              "transaction_id": "ABC123"
                            }
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload. This endpoint doesn't accept 'services'. Remove the services array.",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout.",
                              "transaction_id": "ABC123"
                            }
/booking/create:
    description: Book a journey from a previous quote
    is: [secured, common_errors]
    post:
        description: All requests that require api key
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                     "request_id": "zxyw-98765-tsrp-43567",
                     "quote_id": "abcd-12345-efgh-67890",
                     "service" : "OneFourPassengers",
                     "contacts": {
                        "contact":  {
                          "name": " John Doe",
                          "mobile": "07123 456789",
                          "email": "john.doe@example.com"
                        }
                      },
                     "passengers" : [
                        {
                         "name": " Jane Doe",
                         "mobile": "07262 555555",
                         "email": "jane.doe@example.com"
                         }
                      ],
                      "payment" : {
                        "credit_card":
                          {
                            "pan" : "4000000000000001",
                            "startDate" : "01/13",
                            "expiryDate" : "12/16",
                            "issueNumber" : null,
                            "cvv" : "1",
                            "holderName" : "John Doe",
                            "doorNumber" : "17",
                            "street" : "William Road",
                            "town" : "London",
                            "state" : null,
                            "country" : "GB",
                            "postcode" : "NW1 3ER"
                            },
                          "paypal" :
                          {
                            "payer_id" : "ABCDEFG12345678",
                            "token"    : "EC_123ABC123DEF"
                          }
                       }
                       }
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                              "system_id": "J685000000028974219",
                              "booking_id": "12345",
                              "booking_status" : "booked",
                              "eta" :  5
                            }
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid email address",
                              "transaction_id": "ABC123"
                            }
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout",
                              "transaction_id": "ABC123"
                            }
/booking/amend:
    description: Amend a journey booking
    is: [secured, common_errors]
    post:
        description: All requests that require api key
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                      "job_id" : "J675000000022684775",
                      "pickup_dt" : "2015-12-01T09:00:00+01:00",
                      "start_address" : "35-37 William Road, London, NW1 3ER",
                      "service" : "OneFourPassengers",
                      "locations" : [
                          {
                             "long" : -0.139435,
                             "lat"  : 51.526972
                          },
                          {
                             "long" : -0.239435,
                             "lat"  : 51.326972
                          },
                          {
                             "long" : -0.339435,
                             "lat"  : 51.526972
                          }

                        ]
                      }
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                              "system_id": "J685000000028974219",
                              "booking_id": "12345",
                              "booking_status" : "amended",
                              "eta" :  15
                            }
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid email address",
                              "transaction_id": "ABC123"
                            }
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout",
                              "transaction_id": "ABC123"
                            }
/booking/cancel:
    description: Cancel a journey Booking
    is: [secured, common_errors]
    post:
        description: All requests that require api key
        headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
        body:
            application/json:
                example: |
                    {
                       "job_id" : "J675000000022684775",
                       "pickup_dt" : "2015-10-01T09:00:00+01:00"
                      }
        responses:
            "200":
                body:
                    application/json:
                        example: |
                            {
                              "system_id": "J685000000028974219",
                              "booking_id": "12345",
                              "booking_status" : "cancelled",
                              "total" :  10.00,
                              "vat" : 0.00
                            }
            "400":
                body:
                    application/json:
                        example: |
                            {
                              "status": 400,
                              "code": "USR",
                              "message": "Invalid email address",
                              "transaction_id": "ABC123"
                            }
            "404":
                body:
                    application/json:
                        example: |
                            {
                              "status": 404,
                              "code": "USR",
                              "message": "Invalid or unknown endpoint URI",
                              "transaction_id": "ABC123"
                            }
            "405":
                body:
                    application/json:
                        example: |
                            {
                              "status": 405,
                              "code": "USR",
                              "message": "Invalid HTTP method",
                              "transaction_id": "ABC123"
                            }
            "408":
                body:
                    application/json:
                        example: |
                            {
                              "status": 408,
                              "code": "SYS",
                              "message": "API cannot retrieve an expired value from the cache",
                              "transaction_id": "ABC123"
                            }
            "415":
                body:
                    application/json:
                        example: |
                            {
                              "status": 415,
                              "code": "USR",
                              "message": "Invalid Payload",
                              "transaction_id": "ABC123"
                            }
            "500":
                body:
                    application/json:
                        example: |
                            {
                              "status": 500,
                              "code": "SYS",
                              "message": "API exceeded specified timeout",
                              "transaction_id": "ABC123"
                            }
/address/special:
    description: Get special places addresses
    is: [secured, common_errors]
    post:
      headers:
            Authorization:
                description: The authentication details to use the Acme LTD Quick Book API. The client id and client secret should be passed as follows for all endpoints in the following format
                type: string
                required: true
                repeat: false
                example: "AL ABC1234567899:XYZ9876564321"
      body:
        application/json:
          example: |
            {
               "places" : [
                 {
                   "type" : "Airports"
                 },
                 {
                   "type" : "TrainStations"
                 },
                 {
                  "type" : "TubeStations"
                 }
               ],
               "listing":"All"
              }
      responses:
        200:
          body:
            application/json:
              example: |
                   {
                          "result": "OK",
                          "addresses": [
                            [{
                              "address": "Heathrow, Term 1 (domestic)",
                              "name": "Heathrow, Term 1 (domestic)",
                              "source": "Airport",
                              "town": "London",
                              "postcode": "TW6 1AP",
                              "lat": 51.471959,
                              "long": -0.452201
                            }, {
                              "address": "Heathrow, Term 1 (international)",
                              "name": "Heathrow, Term 1 (international)",
                              "source": "Airport",
                              "town": "London",
                              "postcode": "TW6 1AP",
                              "lat": 51.472,
                              "long": -0.4526
                            }]
                          ]
                        }
/flights/details:
  description: Returns arrival flight details
  is: [secured, common_errors]
  post:
    body:
      application/json:
        example: |
         {
          "date" : "2016-03-16",
          "flight_number" : "BA1487",
          "type" : "arrival"
         }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "result": "OK",
                "flights": [
                    {
                      "number": "BA1487",
                      "departure_airport": "Glasgow International Airport",
                      "arrival_airport": "London Heathrow Apt, Term 5 (domestic)",
                      "arrival_time": "15:15:00",
                      "departure_time": "13:50:00"
                    }
                  ]
              }
