#%RAML 0.8
baseUri: https://mocksvc.devx.mulesoft.com/mocks/9fc066e8-0160-4dea-bc15-41a6d6a6d57b #
title: schema example
/resource:
  post:
    responses:
      200:
        body:
          application/json:
            description: |
              This is a test description of a JSON schema content.
            schema: |
              {
                "prop1" : "string",
                "prop2" : "boolean"
              }
          application/xml:
            description: |
              This is a test description of an XML schema content.

              I wonder how will it be rendered!
            schema: |
              <xs:schema attributeFormDefault="unqualified"
                         elementFormDefault="qualified"
                         xmlns:xs="http://www.w3.org/2001/XMLSchema">
                <xs:element name="api-request">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="xs:string" name="input"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:schema>
  get:
    responses:
      200:
        body:
          application/json:
            description: |
              This is a test description of a JSON schema content.
            schema: |
              {
                "prop1" : "string",
                "prop2" : "boolean"
              }
            example: |
              {
                "input": "s3://zencodertesting/test.mov"
              }
          application/xml:
            description: |
              This is a test description of an XML schema content.

              I wonder how will it be rendered!
            schema: |
              <xs:schema attributeFormDefault="unqualified"
                         elementFormDefault="qualified"
                         xmlns:xs="http://www.w3.org/2001/XMLSchema">
                <xs:element name="api-request">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="xs:string" name="input"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:schema>
            example: |
              <api-request>
                <input>s3://zencodertesting/test.mov</input>
              </api-request>
